version: "3.3"
services:
  webui:
    container_name: HB_project
    image: HB_project:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - "../.env"
    volumes:
      - ../:/data/app/
    ports:
      - "3001:3001"
    restart: always
