version: "3.3"
services:
  webui:
    container_name: json-dynamic-form-project
    image: json-dynamic-form-project:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - "../.env"
    volumes:
      - ../:/data/app/
    ports:
      - "3003:3003"
    restart: always
